version: '3.8'
name: spark-cluster-docker
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=false
      - SPARK_RPC_ENCRYPTION_ENABLED=false
      - SPARK_SSL_ENABLED=false
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077" # Spark Master Port
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      # - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_MEMORY=256m
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge